### ISSUE TITLE
where is gnome-extensions

### ISSUE THREAD

**Issue by weichanghe** [ahmafi/gnome-activities-workspace-name#1]
1  it looks like our IT guies have not installed  gnome-extensions command  in Centos7.9 gnome desktop. I cannot find it in /bin, /usr/bin, /usr/sbin,...  run 'locate  gnome-extensions' has also not find this utility.
even more I have not find any instruction how to install gnome-extensions in Internet.
So, I cannot run 'make install' and 'make run' successfully.
I just do it manually:
download your extension.js and metadata.json-> 'mkdir...   and cp .... '->gnome-tweak enable 'user themes' ->kill current vnc session->vncserver->access  new vnc port->gsettings set...->Alt F2->restart,   there is still no show workspace_name.
2 since just only use one command 'gsettings set...'  can  modify workspace name directly,  I think just one command is enough, I cannot understand why  there is a long guide to describe activate workspace name? 
3 because my Linux permission is just a normal user without root account, I cannot identify my desktop is wayland or X11?  I have tried both 'dbus..' and 'press Alt F2->restart',
still no see workspace name
4 you have provide a picture, I can see any workspace name such as workspace1, workspace2, workspace3, ... from the picture

**Comment by ahmafi** [comment]
1- If you don't have `gnome-extension`, you can just copy the `src` directory content into extensions directory, then restart your gnome-shell.

```
mkdir $HOME/.local/share/gnome-shell/extensions/activitiesworkspacename@ahmafi.ir
cp ./src/* $HOME/.local/share/gnome-shell/extensions/activitiesworkspacename@ahmafi.ir
```

2- I'm not sure what do mean by long guide, I didn't provide a long guide about this anywhere.

3 - There are many ways to know if you are in Wayland or X11. You can check it in `Settings (gnome control center) -> About -> Windowing System` or `echo $XDG_SESSION_TYPE` or [other methods](https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used).

4 - About the picture you are right, I'll change it, so it's more obvious with the example, the workspace name I used was "work" which was shown in the top left where the "Activities" was before.

**Comment by weichanghe** [comment]
Thanks for your reply firstly.
​I have mkdir and cp,
​Aplt F2->restart->gsettings set org.gnome.desktop.wm.preferences workspace-names "['workspace1', 'workspace2', 'workspace3']"
​Unfortunately, there is no display workspace1,workspace2,workspace3 in bottom panel in gnome desktop.
​but run gsettings set org.gnome.desktop.wm.preferences num-workspaces "20", it can create 20 workspace immediately.
so, as a normal linux user(without IT root account), Do you  know how to display workspace_name  in bottom panel in desktop?
Thankd.

**Comment by ahmafi** [comment]
What is your GNOME version?

I'm not sure about the bottom panel. Are you using other extensions to move the panel to the bottom?

**Comment by weichanghe** [comment]
we use CentOS7.9, 
gnome-control-center->Details->About->GONME: Version 3.28.2.
I am not sure we whether other extensions move panel to bottom.
when I login another centos6.9 by vncserver->vncviewer, workspace panel is also located in bottom in the desktop, I can setting workspace num and name very easily just by right mouse button.
in centos7.9, workspace panel is also located in bottom in the desktop, it can set num of workspaces, but cannot set workspace's name.
I search a workspace picture from Internet, our centos6 and centos7 workspace style is like this.

![20221013142339-1665642219714-n mm bing net_th_id_R-C e7d3bd917f5261ab2e4e5a3](https://user-images.githubusercontent.com/115655622/195524365-afc7eeed-3f67-4f85-b242-5301facefc1b.jpg)

**Comment by ahmafi** [comment]
Firstly, this extension only supports and is tested on GNOME 42 and above. You can check this is [GNOME Shell Extension website](https://extensions.gnome.org/extension/5311/activities-workspace-name/).

Secondly, from the screenshot you send and the fact that your panel is in the bottom, you are probably using some extension or modified version of GNOME.
You can check `$HOME/.local/share/gnome-shell/extensions` and `/usr/share/gnome-shell/extensions` to see if you are using any other extensions (There might be located somewhere else if your system administrator changed something).

**Comment by weichanghe** [comment]
Hi, ahmafi,
Thanks for your explanation.

I have checked /usr/share/gnome-shell/extensions, 
there are:
user-theme@xx,
launch-new-instance@xx,
alternate-tab@xx,
window-list@xx,
places-menu@xx,
apps-menu@xx,
top-icons@xx,
horizontal-workspaces@xx.
all metadata.json of above 8 extensions have a "shell-version": ["3.28"].
and then I run gnome-tweaks command, then open 'Extensions' section, it looks like: 
1 Alternatetab  ⚙️, gear can be adjusted.
2 User themes      ON
3 Window list ⚙️, gear can be adjusted.
other extensions line are gray, cannot toggle 'ON' or 'OFF'.
