### ISSUE TITLE
Add ability to rename workspace

### ISSUE THREAD

**Issue by karypid** [ahmafi/gnome-activities-workspace-name#4]

**Comment by dastier** [comment]
It is described in the README:
`gsettings set org.gnome.desktop.wm.preferences workspace-names "['workspace1', 'workspace2', 'workspace3']"`

**Comment by karypid** [comment]
Would it be possible to implement this from the extension (e.g. on right-click a dialogue shows up allowing you to edit) or does the extensions API not allow for that?

**Comment by ahmafi** [comment]
I think it's possible to do. But since it was a simple 1 line command to edit the names, I didn't want to put the effort for that. I might do it in the future. Also, if you are interested, you can create a PR.

**Comment by karypid** [comment]
I used a timer to detect "long click" on the button. In that case a modal dialog is shown that allows you to change the name.

Please note that I've never written JavaScript code, nor any Gnome extension (this is the result of less than a day's web searches on how to write a gnome shell extension).

It works for me so I am currently running it myself. Let me know if you would like to modify something (or just go ahead and edit to your liking).
